import streamlit as st

st.set_page_config(page_title="My Webpage" , page_icon=":tada:", layout="wide")
with st.container():
    st.subheader("Hi, I am Rohith :wave:")
    st.title(" A College Student")
    st.write("This is the website created by me")
    st.write("The scoreboard showed 13 runs required off 6 balls. I was nervous. It was a very important game to us, as it was the finals. The first ball bowled was a dot. 5 balls 13 runs remaining. The coach and the non-striker came up to me and said, “Calm down. You can do it.” I was very much determined to win the game for my team. And Alas! I’ve done it. I hit two consecutive sixes and made my team win. We were the CHAMPIONS. My self-confidence is what made me achieve it. ")
    st.write("In grade 9, I was one of the shortlisted students for the selection of the school cabinet for the year 2020-2021. First we had an interview with our teachers. Then, we were given a topic and asked to provide a solution for it. I was able to do it perfectly. The problem that was given to me made me think out of the box and do things extraordinarily. I’ve always dreamt of being the captain and I have achieved it. The saying,” If you can dream it, you can do it” is true.  All I had was self-belief in myself to achieve it. In this process, I have achieved many things- I could do the difficult tasks easily, it changed my mind-set. My dream came true.")
    st.write("One day I saw an old man on the road searching for an item. He was struggling a lot. There were people walking past him and not helping. My first instinct that came to my mind was to help the old man. I went to him, inquired about what happened. He had lost his vehicle keys. We searched for it for an hour or so and then we found it. I've always believed in the phrase, “Do good, and good will come to you”.")
    st.write("From my childhood, I've been yearning to try many new things. From singing songs to learning how to make different things useful to people. I was interested in new experiences. I've started doing things such as social services, creating websites, etc. That is the point i have realized that change in our society can be brought by ourselves. No matter which profession you choose, I have always felt that we need to excel in those and it should be useful.")
    st.write("I was in the fourth-grade when I changed schools. Everything was new to me. It took a few days for me to mingle with everyone. I used to feel tense talking to teachers. But then there were all the teachers of my school who gave me confidence to speak out. It was the time for our class to perform the Class assembly. Our class teacher came to us and discussed the topic. Our topic was based on the rainbow. My teacher chose me to be the colour “INDIGO”. I had stage fear. I was very scared. The day arrived! The program started smoothly. My friends have completed their part with high and it was my turn. I have stopped thinking about everything and spoke my dialogues loud and clear. After completing the program our teacher came to us and appreciated everyone. She came to me and told me that I had done a very good job. I guess that was the turning point of my life. I became very confident in everything. Whatever work was given to me, I would take it up without any hesitation and successfully complete it. Fast forward, these skills and values made me “the vice-captain of Sapphire Knights” in the grade 9 and “The School captain” in the grade 10.")




